

--Bac si


EXEC sp_addlogin '987654321', '12345', 'DOANHQT';  
GO

GO
CREATE ROLE NHASIROLE;

EXEC sp_addrolemember 'NHASIROLE', [987654321];
GRANT SELECT, INSERT, UPDATE ON HoSoBN TO NHASIROLE
GRANT SELECT, INSERT, UPDATE ON NHASI TO NHASIROLE
GRANT SELECT, INSERT, UPDATE, DELETE ON CT_HOADON TO NHASIROLE
GRANT SELECT, INSERT, UPDATE, DELETE ON LichCaNhanNS TO NHASIROLE
GRANT SELECT, INSERT, UPDATE, DELETE ON HoSoBN TO NHASIROLE
GRANT SELECT ON DichVu TO NHASIROLE
GRANT SELECT ON Thuoc TO NHASIROLE